# Generated by Django 5.2.10 on 2026-03-13 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_id', models.CharField(max_length=255, unique=True)),
                ('border_no', models.CharField(max_length=50, unique=True)),
                ('reg_no', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('room_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user_meal_status', models.BooleanField(default=True)),
                ('guest_meal_status', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.usersync')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
